version: '3.8'

volumes:
  volume_devopspro:

networks:
  devopspro_net:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - devopspro_net
    volumes:
      - volume_devopspro:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - 8081:8081
    networks:
      - devopspro_net
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis